language: java
jdk: openjdk11

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean test

after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
    on_failure: always